-- MySQL Script generated by MySQL Workbench
-- sob, 23 gru 2017, 19:40:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema obuwie_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema obuwie_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `obuwie_db` DEFAULT CHARACTER SET utf8 ;
USE `obuwie_db` ;

-- -----------------------------------------------------
-- Table `obuwie_db`.`klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`klienci` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NOT NULL,
  `nazwa_skrot` VARCHAR(45) NOT NULL,
  `miasto` VARCHAR(45) NOT NULL,
  `kod_pocztowy` VARCHAR(45) NOT NULL,
  `ulica` VARCHAR(45) NOT NULL,
  `numer` VARCHAR(25) NOT NULL,
  `tel` VARCHAR(10) NULL,
  `tel_kom1` VARCHAR(10) NULL,
  `tel_kom2` VARCHAR(10) NULL,
  `fax` VARCHAR(10) NULL,
  `mail` VARCHAR(45) NULL,
  `uwagi` VARCHAR(345) NULL,
  `zamowione` INT NOT NULL DEFAULT 0,
  `odebrane` INT NOT NULL DEFAULT 0,
  `nieodebrane` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_nazwy_skr` (`nazwa_skrot` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`zamowienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`zamowienia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nr_zamowienia` VARCHAR(45) NOT NULL,
  `nazwa_klienta` VARCHAR(45) NULL,
  `id_klienta` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zamowienia_1_idx` (`id_klienta` ASC),
  CONSTRAINT `zam_wg_klienta`
    FOREIGN KEY (`nazwa_klienta`)
    REFERENCES `obuwie_db`.`klienci` (`nazwa_skrot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_1`
    FOREIGN KEY (`id_klienta`)
    REFERENCES `obuwie_db`.`klienci` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`spody`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`spody` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nr_spodu` INT NULL,
  `nazwa` VARCHAR(45) NULL,
  `producent` VARCHAR(45) NULL,
  `rozmiary` VARCHAR(45) NULL,
  `rodzaj` VARCHAR(45) NULL,
  `zdj1` BLOB NULL,
  `zdj2` BLOB NULL,
  `zdj3` BLOB NULL,
  `zdj4` BLOB NULL,
  `uwagi` VARCHAR(400) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_spodu` (`nr_spodu` ASC),
  INDEX `index3` (`nazwa` ASC),
  INDEX `index4` (`producent` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`wzory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`wzory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nr_wzoru` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_wzoru` (`nr_wzoru` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`matryce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`matryce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  `info_nazwa` VARCHAR(225) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_nazwy` (`nazwa` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`kolor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`kolor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kolor` INT NULL,
  `sk1` VARCHAR(25) NULL,
  `dost_sk1` VARCHAR(25) NULL,
  `sk2` VARCHAR(25) NULL,
  `dost_sk2` VARCHAR(25) NULL,
  `sk3` VARCHAR(25) NULL,
  `dost_sk3` VARCHAR(25) NULL,
  `kolor_sk_dominujacy` VARCHAR(25) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_koloru` (`kolor` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`ocieplenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`ocieplenia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_ocieplenia` (`rodzaj` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`wkladka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`wkladka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(245) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_wkladki` (`rodzaj` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`skora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`skora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  `dostawca` VARCHAR(25) NULL,
  `aktualna_cena` REAL NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazwa_UNIQUE` (`nazwa` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`modele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`modele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nr_modelu` INT NOT NULL,
  `nr_wzoru` INT NOT NULL,
  `matryca` VARCHAR(25) NOT NULL,
  `ocieplenie` VARCHAR(25) NOT NULL,
  `spod` INT NOT NULL,
  `spod_nazwa` VARCHAR(45) NULL,
  `spod_prod` VARCHAR(45) NULL,
  `kolor` INT NOT NULL,
  `wkladka` VARCHAR(45) NOT NULL,
  `bok1` BLOB NULL,
  `bok2` BLOB NULL,
  `zdj_spod` BLOB NULL,
  `przyszwa` BLOB NULL,
  `opis1` VARCHAR(45) NULL,
  `opis2` VARCHAR(45) NULL,
  `skora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_spodu` (`spod` ASC),
  UNIQUE INDEX `wg_wzoru` (`nr_wzoru` ASC),
  UNIQUE INDEX `wg_matrycy` (`matryca` ASC),
  UNIQUE INDEX `wg_skory` (`kolor` ASC),
  UNIQUE INDEX `wg_ocieplenia` (`ocieplenie` ASC),
  UNIQUE INDEX `nr_modelu` (`nr_modelu` ASC),
  INDEX `fk_modele_wkladka1_idx` (`wkladka` ASC),
  INDEX `fk_modele_skora1_idx` (`skora_id` ASC),
  INDEX `fk_modele_1_idx` (`spod_nazwa` ASC),
  INDEX `fk_modele_2_idx` (`spod_prod` ASC),
  CONSTRAINT `wg_spodu`
    FOREIGN KEY (`spod`)
    REFERENCES `obuwie_db`.`spody` (`nr_spodu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wg_wzoru`
    FOREIGN KEY (`nr_wzoru`)
    REFERENCES `obuwie_db`.`wzory` (`nr_wzoru`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wg_matrycy`
    FOREIGN KEY (`matryca`)
    REFERENCES `obuwie_db`.`matryce` (`nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wg_skory`
    FOREIGN KEY (`kolor`)
    REFERENCES `obuwie_db`.`kolor` (`kolor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wg_ocieplenia`
    FOREIGN KEY (`ocieplenie`)
    REFERENCES `obuwie_db`.`ocieplenia` (`rodzaj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_wkladka1`
    FOREIGN KEY (`wkladka`)
    REFERENCES `obuwie_db`.`wkladka` (`rodzaj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_skora1`
    FOREIGN KEY (`skora_id`)
    REFERENCES `obuwie_db`.`skora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_1`
    FOREIGN KEY (`spod_nazwa`)
    REFERENCES `obuwie_db`.`spody` (`nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_2`
    FOREIGN KEY (`spod_prod`)
    REFERENCES `obuwie_db`.`spody` (`producent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`statusy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`statusy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`handlowce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`handlowce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(100) NOT NULL,
  `skrot` VARCHAR(45) NOT NULL,
  `uwagi` VARCHAR(345) NULL,
  `nazwa_handlowca` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index2` (`skrot` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`zamowienia_modele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`zamowienia_modele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zamowienia_id` INT NOT NULL,
  `wzor` INT NOT NULL,
  `ocieplenie` VARCHAR(25) NOT NULL,
  `spod` INT NOT NULL,
  `matryca` VARCHAR(25) NOT NULL,
  `kolor` INT NOT NULL,
  `wkladka` VARCHAR(45) NULL,
  `R36` INT NULL,
  `R37` INT NULL,
  `R38` INT NULL,
  `R39` INT NULL,
  `R40` INT NULL,
  `R41` INT NULL,
  `R42` INT NULL,
  `R43` INT NULL,
  `R44` INT NULL,
  `R45` INT NULL,
  `R46` INT NULL,
  `R47` INT NULL,
  `R48` INT NULL,
  `R49` INT NULL,
  `R50` INT NULL,
  `suma` INT NULL,
  `zdjecie` BLOB NULL,
  `sk1` VARCHAR(45) NULL,
  `sk2` VARCHAR(45) NULL,
  `sk3` VARCHAR(45) NULL,
  `spod_nazwa` VARCHAR(45) NULL,
  `spod_prod` VARCHAR(45) NULL,
  `wprowadzono` DATE NULL,
  `realizacja` DATE NULL,
  `status` VARCHAR(45) NULL,
  `uzytkownik` VARCHAR(45) NULL,
  `modele_id` INT NOT NULL,
  `uwagi` VARCHAR(450) NULL,
  `nazwa_handlowca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `wg_koloru` (`kolor` ASC),
  INDEX `fk_zamowienia_modele_zamowienia1_idx` (`zamowienia_id` ASC),
  INDEX `zam_modele_wg_modelu_idx` (`modele_id` ASC),
  INDEX `zamowienia_modele_wg_ocieplenia_idx` (`ocieplenie` ASC),
  INDEX `zamowienia_modele_wg_spodu_idx` (`spod` ASC),
  INDEX `fk_zamowienia_modele_handlowce1_idx` (`nazwa_handlowca` ASC),
  INDEX `fk_zamowienia_modele_1_idx` (`spod_nazwa` ASC),
  INDEX `fk_zamowienia_modele_2_idx` (`spod_prod` ASC),
  INDEX `fk_zamowienia_modele_3_idx` (`wkladka` ASC),
  CONSTRAINT `zam_wg_matrycy`
    FOREIGN KEY (`matryca`)
    REFERENCES `obuwie_db`.`modele` (`matryca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zam_wg_wzoru`
    FOREIGN KEY (`wzor`)
    REFERENCES `obuwie_db`.`modele` (`nr_wzoru`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zam_wg_koloru`
    FOREIGN KEY (`kolor`)
    REFERENCES `obuwie_db`.`modele` (`kolor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zam_modele_wg_zam`
    FOREIGN KEY (`zamowienia_id`)
    REFERENCES `obuwie_db`.`zamowienia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zam_modele_wg_modelu`
    FOREIGN KEY (`modele_id`)
    REFERENCES `obuwie_db`.`modele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zamowienia_modele_wg_ocieplenia`
    FOREIGN KEY (`ocieplenie`)
    REFERENCES `obuwie_db`.`modele` (`ocieplenie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `zamowienia_modele_wg_spodu`
    FOREIGN KEY (`spod`)
    REFERENCES `obuwie_db`.`modele` (`spod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_modele_handlowce1`
    FOREIGN KEY (`nazwa_handlowca`)
    REFERENCES `obuwie_db`.`handlowce` (`skrot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_modele_1`
    FOREIGN KEY (`spod_nazwa`)
    REFERENCES `obuwie_db`.`modele` (`spod_nazwa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_modele_2`
    FOREIGN KEY (`spod_prod`)
    REFERENCES `obuwie_db`.`modele` (`spod_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_modele_3`
    FOREIGN KEY (`wkladka`)
    REFERENCES `obuwie_db`.`modele` (`wkladka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`cena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`cena` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cena` REAL NULL DEFAULT 0,
  `data` DATE NULL,
  `skora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cena_skora1_idx` (`skora_id` ASC),
  CONSTRAINT `fk_cena_skora1`
    FOREIGN KEY (`skora_id`)
    REFERENCES `obuwie_db`.`skora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
