-- MySQL Script generated by MySQL Workbench
-- czw, 22 lut 2018, 20:58:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema obuwie_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema obuwie_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `obuwie_db` DEFAULT CHARACTER SET utf8 ;
USE `obuwie_db` ;

-- -----------------------------------------------------
-- Table `obuwie_db`.`klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`klienci` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NOT NULL,
  `nazwa_skrot` VARCHAR(45) NOT NULL,
  `miasto` VARCHAR(45) NOT NULL,
  `kod_pocztowy` VARCHAR(45) NOT NULL,
  `ulica` VARCHAR(45) NOT NULL,
  `numer` VARCHAR(25) NOT NULL,
  `tel` VARCHAR(10) NULL,
  `tel_kom1` VARCHAR(10) NULL,
  `tel_kom2` VARCHAR(10) NULL,
  `fax` VARCHAR(10) NULL,
  `mail` VARCHAR(45) NULL,
  `uwagi` VARCHAR(345) NULL,
  `zamowione` INT NOT NULL DEFAULT 0,
  `odebrane` INT NOT NULL DEFAULT 0,
  `nieodebrane` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `index3` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`spody`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`spody` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nr` INT NULL,
  `nazwa` VARCHAR(45) NULL,
  `producent` VARCHAR(45) NULL,
  `rozmiary` VARCHAR(45) NULL,
  `rodzaj` VARCHAR(45) NULL,
  `zdj1` BLOB NULL,
  `zdj2` BLOB NULL,
  `zdj3` BLOB NULL,
  `zdj4` BLOB NULL,
  `uwagi` VARCHAR(400) NULL,
  PRIMARY KEY (`id`),
  INDEX `index3` (`nazwa` ASC),
  INDEX `index4` (`producent` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`wzory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`wzory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nr_wzoru` INT NULL,
  `opis` VARCHAR(300) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`kolor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`kolor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kolor` INT NULL,
  `sk1` VARCHAR(25) NULL,
  `dost_sk1` VARCHAR(25) NULL,
  `sk2` VARCHAR(25) NULL,
  `dost_sk2` VARCHAR(25) NULL,
  `sk3` VARCHAR(25) NULL,
  `dost_sk3` VARCHAR(25) NULL,
  `kolor_sk_dominujacy` VARCHAR(25) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_koloru` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`ocieplenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`ocieplenia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_ocieplenia` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`wkladka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`wkladka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_wkladki` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`skora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`skora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  `dostawca` VARCHAR(25) NULL,
  `aktualna_cena` REAL NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nazwa_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`matryce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`matryce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  `info_nazwa` VARCHAR(225) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wg_nazwy` (`nazwa` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`modele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`modele` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wzory_id` INT NOT NULL,
  `matryce_id` INT NOT NULL,
  `ocieplenie` INT NOT NULL,
  `kolor` INT NOT NULL,
  `wkladka` INT NOT NULL,
  `skora_id` INT NOT NULL,
  `spody_id` INT NOT NULL,
  `opis1` VARCHAR(45) NULL,
  `opis2` VARCHAR(45) NULL,
  `zdj1` BLOB NULL,
  `zdj2` BLOB NULL,
  `zdj3` BLOB NULL,
  `zdj4` BLOB NULL,
  `wys_zdj` INT NULL DEFAULT 1,
  `typ` VARCHAR(25) NULL,
  `rodzaj_montazu` VARCHAR(25) NULL,
  `rodzaj_buta` VARCHAR(25) NULL,
  `rodzaj_buta_2` VARCHAR(25) NULL,
  `rodzaj_buta_3` VARCHAR(25) NULL,
  `rodzaj_buta_4` VARCHAR(25) NULL,
  `rodzaj_buta_5` VARCHAR(25) NULL,
  `rodzaj_buta_6` VARCHAR(25) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modele_wkladka1_idx` (`wkladka` ASC),
  INDEX `fk_modele_skora1_idx` (`skora_id` ASC),
  INDEX `fk_modele_spody1_idx` (`spody_id` ASC),
  INDEX `fk_modele_1_idx` (`matryce_id` ASC),
  INDEX `wg_wzoru_idx` (`wzory_id` ASC),
  CONSTRAINT `wg_wzoru`
    FOREIGN KEY (`wzory_id`)
    REFERENCES `obuwie_db`.`wzory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wg_skory`
    FOREIGN KEY (`kolor`)
    REFERENCES `obuwie_db`.`kolor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wg_ocieplenia`
    FOREIGN KEY (`ocieplenie`)
    REFERENCES `obuwie_db`.`ocieplenia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_wkladka1`
    FOREIGN KEY (`wkladka`)
    REFERENCES `obuwie_db`.`wkladka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_skora1`
    FOREIGN KEY (`skora_id`)
    REFERENCES `obuwie_db`.`skora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_spody1`
    FOREIGN KEY (`spody_id`)
    REFERENCES `obuwie_db`.`spody` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modele_1`
    FOREIGN KEY (`matryce_id`)
    REFERENCES `obuwie_db`.`matryce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`handlowce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`handlowce` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(45) NULL,
  `nazwisko` VARCHAR(100) NOT NULL,
  `skrot` VARCHAR(45) NOT NULL,
  `uwagi` VARCHAR(500) NULL,
  `nazwa_handlowca` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`zamowienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`zamowienia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nr_zamowienia` VARCHAR(45) NULL,
  `id_klienta` INT NOT NULL,
  `R36` INT NULL DEFAULT 0,
  `R37` INT NULL DEFAULT 0,
  `R38` INT NULL DEFAULT 0,
  `R39` INT NULL DEFAULT 0,
  `R40` INT NULL DEFAULT 0,
  `R41` INT NULL DEFAULT 0,
  `R42` INT NULL DEFAULT 0,
  `R43` INT NULL DEFAULT 0,
  `R44` INT NULL DEFAULT 0,
  `R45` INT NULL DEFAULT 0,
  `R46` INT NULL DEFAULT 0,
  `R47` INT NULL DEFAULT 0,
  `R48` INT NULL DEFAULT 0,
  `R49` INT NULL DEFAULT 0,
  `R50` INT NULL DEFAULT 0,
  `suma` INT NULL DEFAULT 0,
  `wprowadzono` DATE NULL,
  `realizacja` DATE NULL,
  `status` VARCHAR(45) NULL,
  `uzytkownik` VARCHAR(45) NULL,
  `uwagi` VARCHAR(450) NULL,
  `uwagi2` VARCHAR(450) NULL,
  `drukowano` INT NULL DEFAULT 0,
  `modele_id` INT NOT NULL,
  `handlowce_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `zam_modele_wg_modelu_idx` (`modele_id` ASC),
  INDEX `fk_zamowienia_klienci1_idx` (`id_klienta` ASC),
  INDEX `fk_zamowienia_handlowce1_idx` (`handlowce_id` ASC),
  CONSTRAINT `zam_modele_wg_modelu`
    FOREIGN KEY (`modele_id`)
    REFERENCES `obuwie_db`.`modele` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_klienci1`
    FOREIGN KEY (`id_klienta`)
    REFERENCES `obuwie_db`.`klienci` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zamowienia_handlowce1`
    FOREIGN KEY (`handlowce_id`)
    REFERENCES `obuwie_db`.`handlowce` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `obuwie_db`.`cena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`cena` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cena` DECIMAL NULL DEFAULT 0,
  `data` DATE NULL,
  `skora_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cena_skora1_idx` (`skora_id` ASC),
  CONSTRAINT `fk_cena_skora1`
    FOREIGN KEY (`skora_id`)
    REFERENCES `obuwie_db`.`skora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`typ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`typ` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`rodzaj_montazu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`rodzaj_montazu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`rodzaj_buta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`rodzaj_buta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`rodzaj_buta_6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`rodzaj_buta_6` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`rodzaj_buta_5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`rodzaj_buta_5` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`rodzaj_buta_2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`rodzaj_buta_2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`rodzaj_buta_4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`rodzaj_buta_4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `obuwie_db`.`rodzaj_buta_3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`rodzaj_buta_3` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

USE `obuwie_db` ;

-- -----------------------------------------------------
-- Placeholder table for view `obuwie_db`.`vmodele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`vmodele` (`id` INT, `nr_wzoru` INT, `spnaz` INT, `kolor` INT, `rodzaj` INT, `nazwa` INT, `wkrodzaj` INT, `typ` INT, `rodzaj_montazu` INT, `rodzaj_buta` INT, `rodzaj_buta_2` INT, `rodzaj_buta_3` INT, `rodzaj_buta_4` INT, `rodzaj_buta_5` INT, `rodzaj_buta_6` INT, `opis1` INT, `opis2` INT, `skk` INT);

-- -----------------------------------------------------
-- Placeholder table for view `obuwie_db`.`vzam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obuwie_db`.`vzam` (`zamowienia_id` INT, `nr_zamowienia` INT, `klnaz` INT, `klnr` INT, `wzn` INT, `spnum` INT, `kol` INT, `ocn` INT, `man` INT, `wklr` INT, `R36` INT, `R37` INT, `R38` INT, `R39` INT, `R40` INT, `R41` INT, `R42` INT, `R43` INT, `R44` INT, `R45` INT, `R46` INT, `R47` INT, `R48` INT, `R49` INT, `R50` INT, `suma` INT, `sk1` INT, `sk2` INT, `sk3` INT, `spn` INT, `spp` INT, `uzytkownik` INT, `skrot` INT, `wprowadzono` INT, `realizacja` INT, `uwagi` INT, `uwagi2` INT, `drukowano` INT, `status` INT, `typ` INT, `rodzaj_montazu` INT, `rodzaj_buta` INT, `rodzaj_buta_2` INT, `rodzaj_buta_3` INT, `rodzaj_buta_4` INT, `rodzaj_buta_5` INT, `rodzaj_buta_6` INT);

-- -----------------------------------------------------
-- View `obuwie_db`.`vmodele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obuwie_db`.`vmodele`;
USE `obuwie_db`;
CREATE or replace VIEW `obuwie_db`.`vmodele` AS
      SELECT 
        `m`.`id` AS `id`,
        `obuwie_db`.`wzory`.`nr_wzoru` AS `nr_wzoru`,
        `sp`.`nr` AS `spnaz`,
        `kol`.`kolor` AS `kolor`,
        `oc`.`rodzaj` AS `rodzaj`,
        `obuwie_db`.`matryce`.`nazwa` AS `nazwa`,
        `wk`.`rodzaj` AS `wkrodzaj`,
        `m`.`typ` AS `typ`,
        `m`.`rodzaj_montazu` AS `rodzaj_montazu`,
        `m`.`rodzaj_buta` AS `rodzaj_buta`,
        `m`.`rodzaj_buta_2` AS `rodzaj_buta_2`,
        `m`.`rodzaj_buta_3` AS `rodzaj_buta_3`,
        `m`.`rodzaj_buta_4` AS `rodzaj_buta_4`,
        `m`.`rodzaj_buta_5` AS `rodzaj_buta_5`,
        `m`.`rodzaj_buta_6` AS `rodzaj_buta_6`,
        `m`.`opis1` AS `opis1`,
        `m`.`opis2` AS `opis2`,
        `sk`.`nazwa` AS `skk`
    FROM
        (((((((`obuwie_db`.`modele` `m`
        JOIN `obuwie_db`.`wzory` ON ((`m`.`wzory_id` = `obuwie_db`.`wzory`.`id`)))
        JOIN `obuwie_db`.`matryce` ON ((`m`.`matryce_id` = `obuwie_db`.`matryce`.`id`)))
        JOIN `obuwie_db`.`ocieplenia` `oc` ON ((`m`.`ocieplenie` = `oc`.`id`)))
        JOIN `obuwie_db`.`spody` `sp` ON ((`m`.`spody_id` = `sp`.`id`)))
        JOIN `obuwie_db`.`kolor` `kol` ON ((`m`.`kolor` = `kol`.`id`)))
        JOIN `obuwie_db`.`wkladka` `wk` ON ((`m`.`wkladka` = `wk`.`id`)))
        JOIN `obuwie_db`.`skora` `sk` ON ((`m`.`skora_id` = `sk`.`id`)));

-- -----------------------------------------------------
-- View `obuwie_db`.`vzam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `obuwie_db`.`vzam`;
USE `obuwie_db`;
CREATE or replace VIEW `obuwie_db`.`vzam` AS
        SELECT 
        `z`.`id` AS `zamowienia_id`,
        `z`.`nr_zamowienia` AS `nr_zamowienia`,
        `k`.`nazwa_skrot` AS `klnaz`,
        `k`.`id` AS `klnr`,
        `wz`.`nr_wzoru` AS `wzn`,
        `sp`.`nr` AS `spnum`,
        `kol`.`kolor` AS `kol`,
        `o`.`rodzaj` AS `ocn`,
        `ma`.`nazwa` AS `man`,
        `wk`.`rodzaj` AS `wklr`,
        `z`.`R36` AS `R36`,
        `z`.`R37` AS `R37`,
        `z`.`R38` AS `R38`,
        `z`.`R39` AS `R39`,
        `z`.`R40` AS `R40`,
        `z`.`R41` AS `R41`,
        `z`.`R42` AS `R42`,
        `z`.`R43` AS `R43`,
        `z`.`R44` AS `R44`,
        `z`.`R45` AS `R45`,
        `z`.`R46` AS `R46`,
        `z`.`R47` AS `R47`,
        `z`.`R48` AS `R48`,
        `z`.`R49` AS `R49`,
        `z`.`R50` AS `R50`,
        `z`.`suma` AS `suma`,
        `kol`.`sk1` AS `sk1`,
        `kol`.`sk2` AS `sk2`,
        `kol`.`sk3` AS `sk3`,
        `sp`.`nazwa` AS `spn`,
        `sp`.`producent` AS `spp`,
        `z`.`uzytkownik` AS `uzytkownik`,
        `h`.`skrot` AS `skrot`,
        DATE_FORMAT(`z`.`wprowadzono`, '%m/%d/%Y') AS `wprowadzono`,
        DATE_FORMAT(`z`.`realizacja`, '%m/%d/%Y') AS `realizacja`,
        `z`.`uwagi` AS `uwagi`,
        `z`.`uwagi2` AS `uwagi2`,
        `z`.`drukowano` AS `drukowano`,
        `z`.`status` AS `status`,
        `m`.`typ` AS `typ`,
        `m`.`rodzaj_montazu` AS `rodzaj_montazu`,
        `m`.`rodzaj_buta` AS `rodzaj_buta`,
        `m`.`rodzaj_buta_2` AS `rodzaj_buta_2`,
        `m`.`rodzaj_buta_3` AS `rodzaj_buta_3`,
        `m`.`rodzaj_buta_4` AS `rodzaj_buta_4`,
        `m`.`rodzaj_buta_5` AS `rodzaj_buta_5`,
        `m`.`rodzaj_buta_6` AS `rodzaj_buta_6`
    FROM
        ((((((((((`obuwie_db`.`zamowienia` `z`
        JOIN `obuwie_db`.`klienci` `k` ON ((`z`.`id_klienta` = `k`.`id`)))
        JOIN `obuwie_db`.`modele` `m` ON ((`z`.`modele_id` = `m`.`id`)))
        JOIN `obuwie_db`.`wzory` `wz` ON ((`m`.`wzory_id` = `wz`.`id`)))
        JOIN `obuwie_db`.`ocieplenia` `o` ON ((`m`.`ocieplenie` = `o`.`id`)))
        JOIN `obuwie_db`.`spody` ON ((`m`.`spody_id` = `obuwie_db`.`spody`.`id`)))
        JOIN `obuwie_db`.`matryce` `ma` ON ((`m`.`matryce_id` = `ma`.`id`)))
        JOIN `obuwie_db`.`kolor` `kol` ON ((`m`.`kolor` = `kol`.`id`)))
        JOIN `obuwie_db`.`wkladka` `wk` ON ((`m`.`wkladka` = `wk`.`id`)))
        JOIN `obuwie_db`.`spody` `sp` ON ((`m`.`spody_id` = `sp`.`id`)))
        JOIN `obuwie_db`.`handlowce` `h` ON ((`z`.`handlowce_id` = `h`.`id`)));
USE `obuwie_db`;

DELIMITER $$
USE `obuwie_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `obuwie_db`.`zamowienia_BEFORE_UPDATE` BEFORE UPDATE ON `zamowienia` FOR EACH ROW
BEGIN
SET NEW.suma = NEW.R36 + NEW.R37 + NEW.R38 + NEW.R39+ NEW.R40 + NEW.R41 + NEW.R42+ NEW.R43 + NEW.R44 + NEW.R45 + NEW.R46 + NEW.R47 + NEW.R48 + NEW.R49 + NEW.R50;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
