INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('ATK_SHOTS', 'ATK shots', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('ATK_MISFIRE_SHOTS', 'ATK misfire shots', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('AZ_MOVER_DRIVER_WORK', 'Work of the driver of the azimuth mover', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('AZ_MOVER_ENGINE_WORK', 'Work of the engine of the azimuth mover', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('BS_MOVER_DRIVER_WORK', 'Work of the driver of the mover of the ballistic shell', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('BS_MOVER_ENGINE_WORK', 'Work of the engine of the mover of the ballistic shell', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('COMMANDER_MACH_WORK', 'Work of the commander machine', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('COMMANDER_WCP_WORK', 'Work of the WCP of the commander', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_AKT_OUT', 'Switching of the s_akt_out_enable switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WEAPON', 'Switching of the sw_uzbrojenie switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WEAPON_ACQUISITION', 'Switching of the sw_przejecie_uzbrojenia switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WEAPON_BLOCADE', 'Switching of the sw_blokada_uzbrojenia switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WEAPON_CANNON', 'Switching of the sw_uzb_armata switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WEAPON_CONTROL', 'Switching of the sw_kontrola_amunicji switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WEAPON_PPK', 'Switching of the sw_uzb_ppk switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WEAPON_UKM', 'Switching of the sw_uzb_ukm switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_DRIVERS', 'Switching of the sw_naped switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_EMERGENCY_SHOOTING', 'Switching of the sw_strzelanie_awaryjne switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_FAN', 'Switching of the sw_wentylator switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_L1', 'Switching of the left_joy_L1 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_L2', 'Switching of the left_joy_L2 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_L3', 'Switching of the left_joy_L3 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_L4', 'Switching of the left_joy_L4 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_L5', 'Switching of the left_joy_L5 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_L6', 'Switching of the left_joy_L6 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_DOWN', 'Switching of the left_joy_down switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_LEFT', 'Switching of the left_joy_left switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_RIGHT', 'Switching of the left_joy_right switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_LEFT_JOY_UP', 'Switching of the left_joy_up switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_NO_WEAPON', 'Switching of the sw_uzb_brak switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_RIGHT_JOY_R1', 'Switching of the right_joy_P1 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_RIGHT_JOY_R2', 'Switching of the right_joy_P2 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_RIGHT_JOY_R3', 'Switching of the right_joy_P3 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_RIGHT_JOY_R4', 'Switching of the right_joy_P4 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_RIGHT_JOY_R5', 'Switching of the right_joy_P5 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_RIGHT_JOY_R6', 'Switching of the right_joy_P6 switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_SKO', 'Switching of the sw_sko switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_TRIGGER_OUT', 'Switching of the s_spust_out_enable switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('C_WCP_WORK_MODE', 'Switching of the sw_tryb_pracy switch on the commander''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('DIAGNOSTIC_MACH_WORK', 'Work of the diagnostic machine', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_EMG-T', 'Switching of the turret EMG switch', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_EMG-O', 'Switching of the operator''s EMG switch', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_EMG-C', 'Switching of the commander''s EMG switch', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_TRI', 'Switching of the breakwater sensor', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_DRV', 'Switching of the driver''s hatch sensor', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_SPK', 'Switching of the Spike''s hatch sensor', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_MBL', 'Switching of the left backward hatch sensor', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_DOO', 'Switching of the backward door hatch sensor', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_MBR', 'Switching of the right backward hatch sensor', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('E_TUR', 'Switching of the turret''s comapartment sensor', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('EL_MOVER_DRIVER_WORK', 'Work of the driver of the elevation mover', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('EL_MOVER_ENGINE_WORK', 'Work of the engine of the elevation mover', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('MCLU_WORK', 'Work of the MCLU', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('METEO_AIR_TEMP', 'Air sensor temperature', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('METEO_AMM_TEMP', 'Ammunition sensor temperature', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('METEO_WORK', 'Work of the METEO', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('MLP_CON_ENGINE_WORK', 'Work of the engine of the MLP container', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('MLP_FLAPS_ENGINE_WRK', 'Work of the engine of the MLP flaps', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('MLP_MOV_DRIVER_WORK', 'Work of the driver of the MLP mover', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('OPERATOR_MACH_WORK', 'Work of the operator machine', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('OPERATOR_WCP_WORK', 'Work of the WCP of the operator', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_AKT_OUT', 'Switching of the s_akt_out_enable switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WEAPON', 'Switching of the sw_uzbrojenie switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WEAPON_ACQUISITION', 'Switching of the sw_przejecie_uzbrojenia switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WEAPON_BLOCADE', 'Switching of the sw_blokada_uzbrojenia switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WEAPON_CANNON', 'Switching of the sw_uzb_armata switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WEAPON_CONTROL', 'Switching of the sw_kontrola_amunicji switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WEAPON_PPK', 'Switching of the sw_uzb_ppk switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WEAPON_UKM', 'Switching of the sw_uzb_ukm switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_DRIVERS', 'Switching of the sw_naped switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_EMERGENCY_SHOOTING', 'Switching of the sw_strzelanie_awaryjne switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_FAN', 'Switching of the sw_wentylator switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_L1', 'Switching of the left_joy_L1 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_L2', 'Switching of the left_joy_L2 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_L3', 'Switching of the left_joy_L3 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_L4', 'Switching of the left_joy_L4 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_L5', 'Switching of the left_joy_L5 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_L6', 'Switching of the left_joy_L6 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_DOWN', 'Switching of the left_joy_down switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_LEFT', 'Switching of the left_joy_left switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_RIGHT', 'Switching of the left_joy_right switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_LEFT_JOY_UP', 'Switching of the left_joy_up switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_NO_WEAPON', 'Switching of the sw_uzb_brak switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_RIGHT_JOY_R1', 'Switching of the right_joy_P1 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_RIGHT_JOY_R2', 'Switching of the right_joy_P2 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_RIGHT_JOY_R3', 'Switching of the right_joy_P3 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_RIGHT_JOY_R4', 'Switching of the right_joy_P4 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_RIGHT_JOY_R5', 'Switching of the right_joy_P5 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_RIGHT_JOY_R6', 'Switching of the right_joy_P6 switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_SKO', 'Switching of the sw_sko switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_TRIGGER_OUT', 'Switching of the s_spust_out_enable switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('O_WCP_WORK_MODE', 'Switching of the sw_tryb_pracy switch on the operator''s panel', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('SERVER_MACH_WORK', 'Work of the server machine', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('SPIKE_SHOTS', 'SPIKE shots', 0);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('TALIN_WORK', 'Work of the Talin device', 1);
INSERT INTO `events_types` (`name_of_event_type`, `description_of_event_type`, `point_or_time_interval`) VALUES ('UKM_SHOTS', 'UKM shots', 0);
